### ISSUE TITLE
Get more useful info from the response

### ISSUE THREAD

**Issue by midudev** [d4nidev/carl#5]
Now `carl` returns you the JSON response. In order to improve it and be more useful, it would be nice to add more info from the response, like if the response is being compressed with gzip or brotli, the response time and the content-type returned.

```
Response Status Code: 200
Content-Type: json
Content-Encoding: br

Response:
{ id: 10, name: 'Pikachu' }
```

As `carl` is meant to be a friendly replacement of `curl` maybe, even, the response could be more readable friendly for no technical people.

```
Status Code is 200, that's a OK response. The response is encoded as a JSON and it's compressed with the brotli algorithm which reduced the size in a 32%.

The response of the API was:
{ id: 10, name: 'Pikachu' }
```

**Comment by delacruz-dev** [comment]
@midudev could you please check the [latest release](https://github.com/d4nidev/carl/releases/tag/1.2.0) and tell me if you consider this issue already solved?

**Comment by midudev** [comment]
Yes! :) Well done!
